// Socket

export enum OPCodes {
	DISPATCH = 0,
	HEARTBEAT = 1,
	IDENTIFY = 2,
	PRESENCE_UPDATE = 3,
	VOICE_STATE_UPDATE = 4,
	RESUME = 6,
	RECONNECT = 7,
	REQUEST_GUILD_MEMBERS = 8,
	INVALID_SESSION = 9,
	HELLO = 10,
	HEARTBEAT_ACK = 11
}

export const HELLO_TIMEOUT = 30 * 1000;
export const MAX_CONNECTION_RETRIES = 50;
export const HEARTBEAT_MAX_RESUME_THRESHOLD = 60 * 3 * 1000;

export enum ConnectionState {
	DISCONNECTED,
	DISCOVERING,
	CONNECTING,
	IDENTIFYING,
	RESUMING,
	CONNECTED
}

// Misc
export const BUILD_NUMBER_STRING = 'build_number:"';
export const BUILD_NUMBER_LENGTH = 6;
